name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: thomashoneyman/setup-purescript@master

      - name: Build the project
        run: spago build

      - name: Build the examples
        run: spago build --path 'example/**/*.purs'

      - name: Run tests
        run: spago test
